### ISSUE TITLE
Also release as Firefox Add-on

### ISSUE THREAD

**Issue by jnachtigall** [kylepaulsen/ResourceOverride#17]
Now that Firefox supports the (pretty much) same WebExtensions API like Chrome it would be cool if Ressource Override could be migrated to Firefox too ❤️ 

Ressources:
* https://developer.mozilla.org/en-US/Add-ons/WebExtensions
* https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

**Comment by kylepaulsen** [comment]
Ah yeah, this has been on my mind.. I'll have to look into it... eventually.
I used to have a lot more free time to do OSS. :sweat:

First need to find out what features are not supported and find workarounds.

**Comment by jnachtigall** [comment]
Thanks for considering 👍 

>I used to have a lot more free time to do OSS. 

Sounds familiar :-/

> First need to find out what features are not supported and find workarounds.

You could use the Extension Compatibility Test for this. Just upload your *.crx file to https://www.extensiontest.com/ and it will scan the source code. Normally, every feature in Chrome should also be available in Firefox (bugs aside ;)

**Comment by kylepaulsen** [comment]
Actually, I ended up looking into it tonight because the number of errors the compatibility checker gave me was low...

I made a "quick-fix" alpha branch here: [firefox-alpha](/kylepaulsen/ResourceOverride/tree/firefox-alpha)
One could (for the time being) download this branch and load it into firefox as a debugging extension... although that's kind of a pain. However, I would appreciate the testing. Here's how: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox

So far, my preliminary testing seems to show most everything working. Only real issue I noticed was the dev tools pane not being able to suggest files (which is because devtools.inspectedWindow.getResources() is not supported in FF yet).

I kinda feel like this extension needs a re-write, but seeing how many people use it, I'm afraid to touch it. I may merge this branch once I have more time to test it, at which point I could release it for FF. Any outside testing would be appreciated. I hope someday I can clean things up though and make this a much more modern code base.

**Comment by ashbryant** [comment]
Seems to be working here in FF Developer Edition. You life saver!

**Comment by jnachtigall** [comment]
@kylepaulsen Since this has been used (tested) by a few people for quite some time could it be released on https://addons.mozilla.org/en-US/firefox/? I know the extension is in maintenance mode but at the moment there's just this branch to install from and that's rather complicated compared to just install from the official textensions site (and also unless one uses Firefox Nightly, you also run into problems as this is then a self-signed extension that also need `about:config` workarounds...)

So just to have an upload to https://addons.mozilla.org/en-US/firefox/ would be very much appreciated.

**Comment by kylepaulsen** [comment]
@jnachtigall I will try to do this soon. It seems like it shouldn't require too much effort to get it published.

**Comment by kylepaulsen** [comment]
@jnachtigall @ashbryant It's out now. It seems to work fine, but I didn't test very much.

https://addons.mozilla.org/en-US/firefox/addon/resourceoverride/

**Comment by jnachtigall** [comment]
@kylepaulsen Thank you so much!
