### ISSUE TITLE
CSP rule blocks Resource Override

### ISSUE THREAD

**Issue by mmontag** [kylepaulsen/ResourceOverride#4]
Hello, I think that in some cases the file replacement from Resource Override can be blocked by Content Security Policy headers.

For example, I see this when trying to replace a script: 

![](http://d.pr/i/AeXt.png)

Some Chrome extensions enable CSP override (such as https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden/related?hl=en), but it would be great if the option was bundled in Resource Override.

**Comment by kylepaulsen** [comment]
Hi, thanks for your suggestion. I have added some functionality that will address this in the next version. I'll be releasing it soon!

**Comment by mmontag** [comment]
Cool. The extension works really well – thanks!

**Comment by laukstein** [comment]
@mmontag any reason why this wasn't implemented? I still keep using https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden/ in order to be able to use ResourceOverride extension.

**Comment by kylepaulsen** [comment]
I don't recall the changes I was talking about lol... but I might have meant how you can add header rules now.
If you make a header rule, click into it to edit it, there will be a presets dropdown in the upper right. Look for "allow outside content". Otherwise add "Remove: Content-Security-Policy", "Remove: X-Content-Security-Policy" response headers.
